### ISSUE TITLE
Check that data.csv includes Output2.csv

### ISSUE THREAD

**Issue by rcackerman** [rcackerman/parole-hearing-data#27]
`Output2.csv` has not been deleted because I'm not sure it has been replicated in `data.csv`. Figure out if that's the case, then delete `output2.csv`.

**Comment by talos** [comment]
:+1: Let me know if there's any way I can help!

**Comment by rcackerman** [comment]
Nah, I'll just do this real quick tonight.

**Comment by rcackerman** [comment]
Closed by 042343b
