### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by rcackerman** [rcackerman/parole-hearing-data#31]
The readme no longer reflects the current way to run the scraper... but I'm not sure what the new instructions should be.

**Comment by talos** [comment]
Sorry!  I'm not sure when I'll have a chance to double check/update the readme (not back to work til Tuesday) but the correct procedure should now be:

    python scrape.py input.csv > output.csv 2>errors.txt

In the repo, `input.csv` would generally be `data.csv`.  It's actually optional when you run the script.  After you're done, you'll probably want to move `output.csv` to be the new `data.csv`.

On my list is to create a simple `scrape.sh` or `run.sh` that simply does this as expected.
