### ISSUE TITLE
Merge back in work from my fork

### ISSUE THREAD

**Issue by talos** [rcackerman/parole-hearing-data#34]
I've got a daily scrape running based off of my fork, and pushing updated data to `data.csv`... on my fork.  We should merge this all back in!

**Comment by rcackerman** [comment]
@talos Sorry, I had notifications turned off. Now turned back on!

Is this the work in pull request #35? If so, I've left some comments. Also, do you not have the ability to merge stuff in? Theoretically you're a contributor to this repo, but let me know if you don't have the right permissions.
